spring:
    application:
        name: self-service
    security:
        user:
            name: user
            password: userPass
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: health
    health:
        circuitbreakers:
            enabled: true
server:
    port: 8200

shippingService:
    url: http://localhost:8100
    connectionTimeoutInMillis: 300
    maxHttpPoolSize: 20
    readTimeoutInMillis: 3000
    keepAliveStrategy: 5000

resilience4j:
    circuitbreaker:
        instances:
            shipping-service:
                failure-rate-threshold: 50
                max-wait-duration-in-half-open-state: 10s
                minimumNumberOfCalls: 5
                permitted-number-of-calls-in-half-open-state: 2
                automatic-transition-from-open-to-half-open-enabled: true
                register-health-indicator: true
                sliding-window-size: 10
                sliding-window-type: COUNT_BASED
                wait-duration-in-open-state: 20s
    retry:
        instances:
            shipping-service:
                max-attempts: 2
                wait-duration: 1s
                enable-exponential-backoff: true
                exponential-backoff-multiplier: 2
                randomized-wait-factor: 0.5
                retry-exceptions: [org.springframework.web.client.ResourceAccessException, java.net.SocketTimeoutException, java.io.IOException, java.net.ConnectException]


springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html
